package com.chaomixian.vflow.core.system

import android.app.AutomaticZenRule
import android.app.NotificationManager
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.provider.Settings
import android.service.notification.Condition
import android.service.notification.ZenPolicy

class DndModeManager(private val context: Context) {

    private val notificationManager = 
        context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager

    private val providerComponent = 
        ComponentName(context, DndConditionProviderService::class.java)

    /**
     * Checks if the app has permission to modify Do Not Disturb policy.
     */
    fun hasDndAccess(): Boolean {
        return notificationManager.isNotificationPolicyAccessGranted
    }

    /**
     * Helper to launch DND access settings screen.
     */
    fun requestDndAccess() {
        val intent = Intent(Settings.ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS).apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        context.startActivity(intent)
    }

    /**
     * Creates a custom Do Not Disturb mode (AutomaticZenRule).
     * @param name The name of the mode (e.g., "Gaming Mode", "Sleeping Mode").
     * @param allowStarredCalls If true, priority calls from starred contacts will bypass DND.
     * @param allowAlarms If true, alarms will bypass DND.
     * @return The unique ruleId generated by Android, or null if creation failed/no permission.
     */
    fun createDndMode(
        name: String, 
        allowStarredCalls: Boolean = true, 
        allowAlarms: Boolean = true
    ): String? {
        if (!hasDndAccess()) return null

        // Unique condition identifier Uri for this mode
        val conditionId = Uri.parse("vflow://dnd/rule/${System.currentTimeMillis()}")

        val rule = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            // Android 10+ supports custom ZenPolicies
            val policyBuilder = ZenPolicy.Builder()
                .allowAlarms(allowAlarms)
                .allowReminders(false)
                .allowEvents(false)
                
            if (allowStarredCalls) {
                policyBuilder.allowCalls(ZenPolicy.PEOPLE_TYPE_STARRED)
                policyBuilder.allowRepeatCallers(true)
            } else {
                policyBuilder.allowCalls(ZenPolicy.PEOPLE_TYPE_NONE)
            }

            AutomaticZenRule.Builder(name, conditionId)
                .setOwner(providerComponent)
                .setInterruptionFilter(NotificationManager.INTERRUPTION_FILTER_PRIORITY)
                .setZenPolicy(policyBuilder.build())
                .setEnabled(true)
                .build()
        } else {
            // Fallback for API 23 to 28
            @Suppress("DEPRECATION")
            AutomaticZenRule(
                name,
                providerComponent,
                conditionId,
                NotificationManager.INTERRUPTION_FILTER_PRIORITY,
                true
            )
        }

        return try {
            notificationManager.addAutomaticZenRule(rule)
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }

    /**
     * Toggles a registered DND mode.
     * @param ruleId The unique ID of the rule returned by createDndMode.
     * @param isActive True to activate the mode, false to deactivate.
     */
    fun setDndModeState(ruleId: String, isActive: Boolean): Boolean {
        if (!hasDndAccess()) return false

        val rule = notificationManager.getAutomaticZenRule(ruleId) ?: return false
        val conditionId = rule.conditionId ?: return false

        val state = if (isActive) Condition.STATE_TRUE else Condition.STATE_FALSE
        val summary = if (isActive) "Active via vFlow Workflow" else "Inactive"
        val condition = Condition(conditionId, summary, state)

        return try {
            notificationManager.setAutomaticZenRuleState(ruleId, condition)
            true
        } catch (e: Exception) {
            e.printStackTrace()
            false
        }
    }

    /**
     * Deletes a registered DND mode rule.
     */
    fun deleteDndMode(ruleId: String): Boolean {
        if (!hasDndAccess()) return false
        return try {
            notificationManager.removeAutomaticZenRule(ruleId)
            true
        } catch (e: Exception) {
            e.printStackTrace()
            false
        }
    }

    /**
     * Lists all Zen rules owned by this app.
     */
    fun getRegisteredModes(): Map<String, AutomaticZenRule> {
        if (!hasDndAccess()) return emptyMap()
        return notificationManager.automaticZenRules ?: emptyMap()
    }
}
